name: Sync to Hugging Face Space
on:
  push:
    branches: [main]
jobs:
  sync-to-hf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf https://ManuelZafra:$HF_TOKEN@huggingface.co/spaces/ManuelZafra/Music_Sonar_2.0
          git push hf main --force
